---
- hosts: all
  become: True
  tasks:
   - name: update apt
     apt: update_cache=yes
   - name: Install apache
     apt: name=apache2 state=latest
   - name: Deploy static website
     copy:
      src: index.html
      dest: /var/www/html
